name: WasteDetectionServerApp
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.3.0
  - gdal=3.3.2
  - geojson=2.5.0
  - geopandas=0.12.1
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pandas=1.3.3
  - pillow=8.3.2
  - pip=21.2.4
  - python=3.8.12
  - rasterio=1.2.8
  - scikit-learn=0.24.2
  - sentinelhub=3.4.4
  - shapely=1.7.1
  - pip:
      - jsonmerge==1.9.0
      - opencv-python-headless==4.5.3.56
